sudo: false
dist: trusty
language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - npm install -g --silent @angular/cli

script:
  - npm test
  - ng build --prod
